# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run:
          name: Build Docker Image
          command: docker build -t damdey/booknow:$CIRCLE_SHA1 .

      - run:
          name: Push to Dockerhub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p DOCKERHUB_PASSWORD
            docker push damdey/booknow:$CIRCLE_SHA1

      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY  registry.heroku.com
            docker tag damdey/booknow:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_WEB/web

     # release the image
     - run: |
         heroku -v
         heroku update
         heroku container:release web -a $HEROKU_APP_NAME


